/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quotes;

import org.junit.Test;
import static org.junit.Assert.*;
import com.google.gson.Gson;


public class AppTest {
    @Test
    public void quoteTest(){

        String json = App.readJson();
        Gson gson = new Gson();
        Quote[] quotesArray = gson.fromJson(json, Quote[].class);
        String expected = String.valueOf(quotesArray[0]);
        String actual = "Quote{author='Charles Dickens', '513 likes', text='It was one of those March days when the sun shines hot and the wind blows cold: when it is summer in the light, and winter in the shade.'}" ;
        assertEquals(expected , actual);
    }
}
