/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quotes;
import com.google.gson.Gson;

import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;

public class App {

    public static void main(String[] args) {

        Gson gson = new Gson();
        String jsonFile = readJson();
        Quote[] read = gson.fromJson(jsonFile, Quote[].class);
        int randNum = (int)(Math.random()*read.length);
        System.out.println(read[randNum]);
    }

    public static String readJson() {
        String lines = "";
        String result ="";
        BufferedReader file = null;

        try {
            file = new BufferedReader(new FileReader("app/src/main/resources/ recentquotes.json"));
            lines = file.readLine();
            while (lines != null) {
                result += lines + "\n";
                lines = file.readLine();
            }
            file.close();
        } catch (IOException ioe) {
            ioe.printStackTrace();
        }
        return result;
    }
}
